### ISSUE TITLE
Versions 6.0.0 and up do not work in RUNESCAPE

### ISSUE THREAD

**Issue by antonella777** [OpenMultiBoxing/OpenMultiBoxing#9]
It seems that the new clicking mechanism does not work in Runescape.

**To Reproduce**
It seems to click on all accounts, but neither the right nor the left click is made, this happens with the "broadcast click mouse" and the "broadcast"

**Expected behavior**
I expected it to work correctly as it did in version 5.2.7

**Screenshots**
I don't think it's necessary.

_Important_:
Not applicable.

**Round Robin:**
No.

**Game:**
Runescape.

**Settings:**
Applies to all default settings.

**Error details:**
There is no application error.

**Comment by mooreatv** [comment]
fixed in https://github.com/OpenMultiBoxing/OpenMultiBoxing/commit/d35a90e968cc86ccda114a47b4521e36e9cddb76 (7.0.1)

**Comment by antonella777** [comment]
Thank you very much <3
